#pragma once

// =====================================================================
// AUTO-GENERATED FROM config.toml. DO NOT EDIT THIS FILE DIRECTLY.
// Generated by emotion_detect/script/gen_config_header.py
// =====================================================================

#define DEPLOY_COOLDOWN_MS          5000
#define DEPLOY_JITTER_THRESHOLD_MS  200
#define DEPLOY_HAPTIC_GPIO          4
#define DEPLOY_LED_GPIO             2

#define MODEL_NUM_CLASS             7
#define MODEL_BASE_CHANNELS         32
