device = "cuda" # cuda or cpu


[model]
num_class = 7
num_stage = 2
num_res = 2
dropout = 0.3
base_channels = 8


[data]
path = "archive"
batch_size = 128
num_workers = 6


[train]
epochs = 500
lr = 1e-2
weight_decay = 1e-3
label_smoothing = 0.1 # 0.0 ~ 1.0
mixup_alpha = 0.2 # 0.0 ~ 1.0


[train.early_stop]
enable = true
patience = 20
min_delta = 1e-3


[train.loss]
center_loss_weight = 0.01
center_loss_lr = 0.5
